/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppPoliciesKeyRouteImport } from './routes/_app.policies.key'
import { Route as AppPoliciesHostRouteImport } from './routes/_app.policies.host'
import { Route as AppInventoryHostsRouteImport } from './routes/_app.inventory.hosts'
import { Route as AppDiscoveryStatusRouteImport } from './routes/_app.discovery.status'
import { Route as AppDiscoveryRunsRouteImport } from './routes/_app.discovery.runs'
import { Route as AppDiscoveryProfilesRouteImport } from './routes/_app.discovery.profiles'
import { Route as AppAgentMcpRouteImport } from './routes/_app.agent.mcp'
import { Route as AppAdministrationTagsRouteImport } from './routes/_app.administration.tags'
import { Route as AppAdministrationSettingsRouteImport } from './routes/_app.administration.settings'
import { Route as AppAdministrationDevicesRouteImport } from './routes/_app.administration.devices'
import { Route as AppAdministrationCaRouteImport } from './routes/_app.administration.ca'
import { Route as AppInventoryKeysUserRouteImport } from './routes/_app.inventory.keys.user'
import { Route as AppInventoryKeysRotatedRouteImport } from './routes/_app.inventory.keys.rotated'
import { Route as AppInventoryKeysHostRouteImport } from './routes/_app.inventory.keys.host'
import { Route as AppInventoryKeysDeletedRouteImport } from './routes/_app.inventory.keys.deleted'
import { Route as AppInventoryCertificatesUserRouteImport } from './routes/_app.inventory.certificates.user'
import { Route as AppInventoryCertificatesRotatedRouteImport } from './routes/_app.inventory.certificates.rotated'
import { Route as AppInventoryCertificatesHostRouteImport } from './routes/_app.inventory.certificates.host'
import { Route as AppInventoryCertificatesDeletedRouteImport } from './routes/_app.inventory.certificates.deleted'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesKeyRoute = AppPoliciesKeyRouteImport.update({
  id: '/policies/key',
  path: '/policies/key',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesHostRoute = AppPoliciesHostRouteImport.update({
  id: '/policies/host',
  path: '/policies/host',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryHostsRoute = AppInventoryHostsRouteImport.update({
  id: '/inventory/hosts',
  path: '/inventory/hosts',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryStatusRoute = AppDiscoveryStatusRouteImport.update({
  id: '/discovery/status',
  path: '/discovery/status',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRunsRoute = AppDiscoveryRunsRouteImport.update({
  id: '/discovery/runs',
  path: '/discovery/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryProfilesRoute = AppDiscoveryProfilesRouteImport.update({
  id: '/discovery/profiles',
  path: '/discovery/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentMcpRoute = AppAgentMcpRouteImport.update({
  id: '/agent/mcp',
  path: '/agent/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationTagsRoute = AppAdministrationTagsRouteImport.update({
  id: '/administration/tags',
  path: '/administration/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationSettingsRoute =
  AppAdministrationSettingsRouteImport.update({
    id: '/administration/settings',
    path: '/administration/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationDevicesRoute =
  AppAdministrationDevicesRouteImport.update({
    id: '/administration/devices',
    path: '/administration/devices',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationCaRoute = AppAdministrationCaRouteImport.update({
  id: '/administration/ca',
  path: '/administration/ca',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysUserRoute = AppInventoryKeysUserRouteImport.update({
  id: '/inventory/keys/user',
  path: '/inventory/keys/user',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysRotatedRoute = AppInventoryKeysRotatedRouteImport.update({
  id: '/inventory/keys/rotated',
  path: '/inventory/keys/rotated',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysHostRoute = AppInventoryKeysHostRouteImport.update({
  id: '/inventory/keys/host',
  path: '/inventory/keys/host',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysDeletedRoute = AppInventoryKeysDeletedRouteImport.update({
  id: '/inventory/keys/deleted',
  path: '/inventory/keys/deleted',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCertificatesUserRoute =
  AppInventoryCertificatesUserRouteImport.update({
    id: '/inventory/certificates/user',
    path: '/inventory/certificates/user',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryCertificatesRotatedRoute =
  AppInventoryCertificatesRotatedRouteImport.update({
    id: '/inventory/certificates/rotated',
    path: '/inventory/certificates/rotated',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryCertificatesHostRoute =
  AppInventoryCertificatesHostRouteImport.update({
    id: '/inventory/certificates/host',
    path: '/inventory/certificates/host',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryCertificatesDeletedRoute =
  AppInventoryCertificatesDeletedRouteImport.update({
    id: '/inventory/certificates/deleted',
    path: '/inventory/certificates/deleted',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/administration/ca': typeof AppAdministrationCaRoute
  '/administration/devices': typeof AppAdministrationDevicesRoute
  '/administration/settings': typeof AppAdministrationSettingsRoute
  '/administration/tags': typeof AppAdministrationTagsRoute
  '/agent/mcp': typeof AppAgentMcpRoute
  '/discovery/profiles': typeof AppDiscoveryProfilesRoute
  '/discovery/runs': typeof AppDiscoveryRunsRoute
  '/discovery/status': typeof AppDiscoveryStatusRoute
  '/inventory/hosts': typeof AppInventoryHostsRoute
  '/policies/host': typeof AppPoliciesHostRoute
  '/policies/key': typeof AppPoliciesKeyRoute
  '/inventory/certificates/deleted': typeof AppInventoryCertificatesDeletedRoute
  '/inventory/certificates/host': typeof AppInventoryCertificatesHostRoute
  '/inventory/certificates/rotated': typeof AppInventoryCertificatesRotatedRoute
  '/inventory/certificates/user': typeof AppInventoryCertificatesUserRoute
  '/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/administration/ca': typeof AppAdministrationCaRoute
  '/administration/devices': typeof AppAdministrationDevicesRoute
  '/administration/settings': typeof AppAdministrationSettingsRoute
  '/administration/tags': typeof AppAdministrationTagsRoute
  '/agent/mcp': typeof AppAgentMcpRoute
  '/discovery/profiles': typeof AppDiscoveryProfilesRoute
  '/discovery/runs': typeof AppDiscoveryRunsRoute
  '/discovery/status': typeof AppDiscoveryStatusRoute
  '/inventory/hosts': typeof AppInventoryHostsRoute
  '/policies/host': typeof AppPoliciesHostRoute
  '/policies/key': typeof AppPoliciesKeyRoute
  '/inventory/certificates/deleted': typeof AppInventoryCertificatesDeletedRoute
  '/inventory/certificates/host': typeof AppInventoryCertificatesHostRoute
  '/inventory/certificates/rotated': typeof AppInventoryCertificatesRotatedRoute
  '/inventory/certificates/user': typeof AppInventoryCertificatesUserRoute
  '/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/administration/ca': typeof AppAdministrationCaRoute
  '/_app/administration/devices': typeof AppAdministrationDevicesRoute
  '/_app/administration/settings': typeof AppAdministrationSettingsRoute
  '/_app/administration/tags': typeof AppAdministrationTagsRoute
  '/_app/agent/mcp': typeof AppAgentMcpRoute
  '/_app/discovery/profiles': typeof AppDiscoveryProfilesRoute
  '/_app/discovery/runs': typeof AppDiscoveryRunsRoute
  '/_app/discovery/status': typeof AppDiscoveryStatusRoute
  '/_app/inventory/hosts': typeof AppInventoryHostsRoute
  '/_app/policies/host': typeof AppPoliciesHostRoute
  '/_app/policies/key': typeof AppPoliciesKeyRoute
  '/_app/inventory/certificates/deleted': typeof AppInventoryCertificatesDeletedRoute
  '/_app/inventory/certificates/host': typeof AppInventoryCertificatesHostRoute
  '/_app/inventory/certificates/rotated': typeof AppInventoryCertificatesRotatedRoute
  '/_app/inventory/certificates/user': typeof AppInventoryCertificatesUserRoute
  '/_app/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/_app/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/_app/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/_app/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/administration/ca'
    | '/administration/devices'
    | '/administration/settings'
    | '/administration/tags'
    | '/agent/mcp'
    | '/discovery/profiles'
    | '/discovery/runs'
    | '/discovery/status'
    | '/inventory/hosts'
    | '/policies/host'
    | '/policies/key'
    | '/inventory/certificates/deleted'
    | '/inventory/certificates/host'
    | '/inventory/certificates/rotated'
    | '/inventory/certificates/user'
    | '/inventory/keys/deleted'
    | '/inventory/keys/host'
    | '/inventory/keys/rotated'
    | '/inventory/keys/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/administration/ca'
    | '/administration/devices'
    | '/administration/settings'
    | '/administration/tags'
    | '/agent/mcp'
    | '/discovery/profiles'
    | '/discovery/runs'
    | '/discovery/status'
    | '/inventory/hosts'
    | '/policies/host'
    | '/policies/key'
    | '/inventory/certificates/deleted'
    | '/inventory/certificates/host'
    | '/inventory/certificates/rotated'
    | '/inventory/certificates/user'
    | '/inventory/keys/deleted'
    | '/inventory/keys/host'
    | '/inventory/keys/rotated'
    | '/inventory/keys/user'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/groups'
    | '/_app/administration/ca'
    | '/_app/administration/devices'
    | '/_app/administration/settings'
    | '/_app/administration/tags'
    | '/_app/agent/mcp'
    | '/_app/discovery/profiles'
    | '/_app/discovery/runs'
    | '/_app/discovery/status'
    | '/_app/inventory/hosts'
    | '/_app/policies/host'
    | '/_app/policies/key'
    | '/_app/inventory/certificates/deleted'
    | '/_app/inventory/certificates/host'
    | '/_app/inventory/certificates/rotated'
    | '/_app/inventory/certificates/user'
    | '/_app/inventory/keys/deleted'
    | '/_app/inventory/keys/host'
    | '/_app/inventory/keys/rotated'
    | '/_app/inventory/keys/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies/key': {
      id: '/_app/policies/key'
      path: '/policies/key'
      fullPath: '/policies/key'
      preLoaderRoute: typeof AppPoliciesKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies/host': {
      id: '/_app/policies/host'
      path: '/policies/host'
      fullPath: '/policies/host'
      preLoaderRoute: typeof AppPoliciesHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/hosts': {
      id: '/_app/inventory/hosts'
      path: '/inventory/hosts'
      fullPath: '/inventory/hosts'
      preLoaderRoute: typeof AppInventoryHostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery/status': {
      id: '/_app/discovery/status'
      path: '/discovery/status'
      fullPath: '/discovery/status'
      preLoaderRoute: typeof AppDiscoveryStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery/runs': {
      id: '/_app/discovery/runs'
      path: '/discovery/runs'
      fullPath: '/discovery/runs'
      preLoaderRoute: typeof AppDiscoveryRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery/profiles': {
      id: '/_app/discovery/profiles'
      path: '/discovery/profiles'
      fullPath: '/discovery/profiles'
      preLoaderRoute: typeof AppDiscoveryProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/mcp': {
      id: '/_app/agent/mcp'
      path: '/agent/mcp'
      fullPath: '/agent/mcp'
      preLoaderRoute: typeof AppAgentMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/tags': {
      id: '/_app/administration/tags'
      path: '/administration/tags'
      fullPath: '/administration/tags'
      preLoaderRoute: typeof AppAdministrationTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/settings': {
      id: '/_app/administration/settings'
      path: '/administration/settings'
      fullPath: '/administration/settings'
      preLoaderRoute: typeof AppAdministrationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/devices': {
      id: '/_app/administration/devices'
      path: '/administration/devices'
      fullPath: '/administration/devices'
      preLoaderRoute: typeof AppAdministrationDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/ca': {
      id: '/_app/administration/ca'
      path: '/administration/ca'
      fullPath: '/administration/ca'
      preLoaderRoute: typeof AppAdministrationCaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/user': {
      id: '/_app/inventory/keys/user'
      path: '/inventory/keys/user'
      fullPath: '/inventory/keys/user'
      preLoaderRoute: typeof AppInventoryKeysUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/rotated': {
      id: '/_app/inventory/keys/rotated'
      path: '/inventory/keys/rotated'
      fullPath: '/inventory/keys/rotated'
      preLoaderRoute: typeof AppInventoryKeysRotatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/host': {
      id: '/_app/inventory/keys/host'
      path: '/inventory/keys/host'
      fullPath: '/inventory/keys/host'
      preLoaderRoute: typeof AppInventoryKeysHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/deleted': {
      id: '/_app/inventory/keys/deleted'
      path: '/inventory/keys/deleted'
      fullPath: '/inventory/keys/deleted'
      preLoaderRoute: typeof AppInventoryKeysDeletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/certificates/user': {
      id: '/_app/inventory/certificates/user'
      path: '/inventory/certificates/user'
      fullPath: '/inventory/certificates/user'
      preLoaderRoute: typeof AppInventoryCertificatesUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/certificates/rotated': {
      id: '/_app/inventory/certificates/rotated'
      path: '/inventory/certificates/rotated'
      fullPath: '/inventory/certificates/rotated'
      preLoaderRoute: typeof AppInventoryCertificatesRotatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/certificates/host': {
      id: '/_app/inventory/certificates/host'
      path: '/inventory/certificates/host'
      fullPath: '/inventory/certificates/host'
      preLoaderRoute: typeof AppInventoryCertificatesHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/certificates/deleted': {
      id: '/_app/inventory/certificates/deleted'
      path: '/inventory/certificates/deleted'
      fullPath: '/inventory/certificates/deleted'
      preLoaderRoute: typeof AppInventoryCertificatesDeletedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppAdministrationCaRoute: typeof AppAdministrationCaRoute
  AppAdministrationDevicesRoute: typeof AppAdministrationDevicesRoute
  AppAdministrationSettingsRoute: typeof AppAdministrationSettingsRoute
  AppAdministrationTagsRoute: typeof AppAdministrationTagsRoute
  AppAgentMcpRoute: typeof AppAgentMcpRoute
  AppDiscoveryProfilesRoute: typeof AppDiscoveryProfilesRoute
  AppDiscoveryRunsRoute: typeof AppDiscoveryRunsRoute
  AppDiscoveryStatusRoute: typeof AppDiscoveryStatusRoute
  AppInventoryHostsRoute: typeof AppInventoryHostsRoute
  AppPoliciesHostRoute: typeof AppPoliciesHostRoute
  AppPoliciesKeyRoute: typeof AppPoliciesKeyRoute
  AppInventoryCertificatesDeletedRoute: typeof AppInventoryCertificatesDeletedRoute
  AppInventoryCertificatesHostRoute: typeof AppInventoryCertificatesHostRoute
  AppInventoryCertificatesRotatedRoute: typeof AppInventoryCertificatesRotatedRoute
  AppInventoryCertificatesUserRoute: typeof AppInventoryCertificatesUserRoute
  AppInventoryKeysDeletedRoute: typeof AppInventoryKeysDeletedRoute
  AppInventoryKeysHostRoute: typeof AppInventoryKeysHostRoute
  AppInventoryKeysRotatedRoute: typeof AppInventoryKeysRotatedRoute
  AppInventoryKeysUserRoute: typeof AppInventoryKeysUserRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppAdministrationCaRoute: AppAdministrationCaRoute,
  AppAdministrationDevicesRoute: AppAdministrationDevicesRoute,
  AppAdministrationSettingsRoute: AppAdministrationSettingsRoute,
  AppAdministrationTagsRoute: AppAdministrationTagsRoute,
  AppAgentMcpRoute: AppAgentMcpRoute,
  AppDiscoveryProfilesRoute: AppDiscoveryProfilesRoute,
  AppDiscoveryRunsRoute: AppDiscoveryRunsRoute,
  AppDiscoveryStatusRoute: AppDiscoveryStatusRoute,
  AppInventoryHostsRoute: AppInventoryHostsRoute,
  AppPoliciesHostRoute: AppPoliciesHostRoute,
  AppPoliciesKeyRoute: AppPoliciesKeyRoute,
  AppInventoryCertificatesDeletedRoute: AppInventoryCertificatesDeletedRoute,
  AppInventoryCertificatesHostRoute: AppInventoryCertificatesHostRoute,
  AppInventoryCertificatesRotatedRoute: AppInventoryCertificatesRotatedRoute,
  AppInventoryCertificatesUserRoute: AppInventoryCertificatesUserRoute,
  AppInventoryKeysDeletedRoute: AppInventoryKeysDeletedRoute,
  AppInventoryKeysHostRoute: AppInventoryKeysHostRoute,
  AppInventoryKeysRotatedRoute: AppInventoryKeysRotatedRoute,
  AppInventoryKeysUserRoute: AppInventoryKeysUserRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
