/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInventoryKeysUserRouteImport } from './routes/_app.inventory.keys.user'
import { Route as AppInventoryKeysRotatedRouteImport } from './routes/_app.inventory.keys.rotated'
import { Route as AppInventoryKeysHostRouteImport } from './routes/_app.inventory.keys.host'
import { Route as AppInventoryKeysDeletedRouteImport } from './routes/_app.inventory.keys.deleted'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysUserRoute = AppInventoryKeysUserRouteImport.update({
  id: '/inventory/keys/user',
  path: '/inventory/keys/user',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysRotatedRoute = AppInventoryKeysRotatedRouteImport.update({
  id: '/inventory/keys/rotated',
  path: '/inventory/keys/rotated',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysHostRoute = AppInventoryKeysHostRouteImport.update({
  id: '/inventory/keys/host',
  path: '/inventory/keys/host',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryKeysDeletedRoute = AppInventoryKeysDeletedRouteImport.update({
  id: '/inventory/keys/deleted',
  path: '/inventory/keys/deleted',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory/keys/deleted': typeof AppInventoryKeysDeletedRoute
  '/_app/inventory/keys/host': typeof AppInventoryKeysHostRoute
  '/_app/inventory/keys/rotated': typeof AppInventoryKeysRotatedRoute
  '/_app/inventory/keys/user': typeof AppInventoryKeysUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory/keys/deleted'
    | '/inventory/keys/host'
    | '/inventory/keys/rotated'
    | '/inventory/keys/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inventory/keys/deleted'
    | '/inventory/keys/host'
    | '/inventory/keys/rotated'
    | '/inventory/keys/user'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/inventory/keys/deleted'
    | '/_app/inventory/keys/host'
    | '/_app/inventory/keys/rotated'
    | '/_app/inventory/keys/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/user': {
      id: '/_app/inventory/keys/user'
      path: '/inventory/keys/user'
      fullPath: '/inventory/keys/user'
      preLoaderRoute: typeof AppInventoryKeysUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/rotated': {
      id: '/_app/inventory/keys/rotated'
      path: '/inventory/keys/rotated'
      fullPath: '/inventory/keys/rotated'
      preLoaderRoute: typeof AppInventoryKeysRotatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/host': {
      id: '/_app/inventory/keys/host'
      path: '/inventory/keys/host'
      fullPath: '/inventory/keys/host'
      preLoaderRoute: typeof AppInventoryKeysHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/keys/deleted': {
      id: '/_app/inventory/keys/deleted'
      path: '/inventory/keys/deleted'
      fullPath: '/inventory/keys/deleted'
      preLoaderRoute: typeof AppInventoryKeysDeletedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryKeysDeletedRoute: typeof AppInventoryKeysDeletedRoute
  AppInventoryKeysHostRoute: typeof AppInventoryKeysHostRoute
  AppInventoryKeysRotatedRoute: typeof AppInventoryKeysRotatedRoute
  AppInventoryKeysUserRoute: typeof AppInventoryKeysUserRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryKeysDeletedRoute: AppInventoryKeysDeletedRoute,
  AppInventoryKeysHostRoute: AppInventoryKeysHostRoute,
  AppInventoryKeysRotatedRoute: AppInventoryKeysRotatedRoute,
  AppInventoryKeysUserRoute: AppInventoryKeysUserRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
